version: '3.8'

services:
  tossel-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - tossel_data:/app/backend/prisma
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=file:./dev.db
    restart: always

volumes:
  tossel_data:
